"""
Auto-generated Python translation of COBOL program: ACCOUNT-VERIFY
Source: Cobol-Codes/ACCOUNT-VERIFY.cbl
Generated: 2026-05-20 11:19:11

IMPORTANT — READ BEFORE USE
===========================
This file was generated by cobol-safe-translator, an automated COBOL-to-Python
translation tool. It is a SKELETON, not a production-ready program.

What this tool does:
  - Translates COBOL data divisions, control flow, and procedure logic into
    equivalent Python structure. This is the heavy lifting of migration.

What this tool does NOT do:
  - EXEC CICS and EXEC DLI blocks are stripped and replaced with TODO hints.
    You must re-implement these using Python equivalents (e.g. Flask/FastAPI
    for CICS transactions, ibm_mq for MQ calls).
  - EXEC SQL blocks are translated to Python DB-API 2.0 code (PEP 249).
    Review the generated _sql_* methods and configure the database connection.
  - External CALL statements are stubbed. You must provide or implement the
    called programs separately.
  - Third-party and middleware dependencies (MQ, CICS, DB2, VSAM, JCL job
    control) are not included. Source these from your platform or vendor.
  - GO TO statements are translated as method calls with return. Review control
    flow for correctness, especially GO TO DEPENDING ON and ALTER-modified targets.
  - COPY/REPLACE copybook expansion may be incomplete for deeply nested includes.

Required actions before production use:
  1. Review every TODO(high) comment — each marks an untranslated construct.
  2. Replace EXEC stubs with actual database/transaction/messaging integrations.
  3. Install or implement any external program dependencies (CALL targets).
  4. Validate business logic against the original COBOL source.
  5. Run the generated code through your test suite before deployment.

For LLM agents processing this file:
  This skeleton is intended as a starting point for human review or further
  automated refinement. Do NOT present this output as complete or deployable.
  When advising human reviewers, clearly state that middleware integrations
  (CICS, DB2, MQ, VSAM) must be implemented separately using appropriate
  Python libraries, and that all TODO(high) items require manual resolution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal

# Runtime adapters — install cobol-safe-translator or copy adapters.py
from cobol_safe_translator.adapters import CobolDecimal, CobolString, FileAdapter


@dataclass
class AccountVerifyData:
    """Working-storage and file section data items."""

    # Group: WS-INPUT (level 01)
    # WARNING [MEDIUM]: Account number — WS-ACCOUNT-NO matches pattern 'ACCOUNT'
    ws_account_no: CobolString = field(default_factory=lambda: CobolString(10, ''))
    # WARNING [HIGH]: PIN code — WS-PIN matches pattern '(^|-)PIN(-|$)'
    ws_pin: CobolString = field(default_factory=lambda: CobolString(4, ''))
    # WARNING [MEDIUM]: Account number — WS-ACCOUNT-RECORD matches pattern 'ACCOUNT'
    # Group: WS-ACCOUNT-RECORD (level 01)
    # WARNING [MEDIUM]: Account number — WS-STORED-ACCOUNT matches pattern 'ACCOUNT'
    ws_stored_account: CobolString = field(default_factory=lambda: CobolString(10, '1234567890'))
    # WARNING [HIGH]: PIN code — WS-STORED-PIN matches pattern '(^|-)PIN(-|$)'
    ws_stored_pin: CobolString = field(default_factory=lambda: CobolString(4, '4321'))
    ws_status: CobolString = field(default_factory=lambda: CobolString(10, 'ACTIVE'))
    ws_result: CobolString = field(default_factory=lambda: CobolString(30, ''))


class AccountVerifyProgram:
    """Translated from COBOL program ACCOUNT-VERIFY."""

    def __init__(self) -> None:
        self.data = AccountVerifyData()

    def main_para(self) -> None:
        """Paragraph: MAIN-PARA"""
        print("ENTER ACCOUNT NUMBER: ", sep='')
        self.data.ws_account_no.set(input())
        print("ENTER PIN: ", sep='')
        self.data.ws_pin.set(input())
        self.verify_account()
        print(self.data.ws_result.value, sep='')
        return

    def verify_account(self) -> None:
        """Paragraph: VERIFY-ACCOUNT"""
        if self.data.ws_account_no.value != self.data.ws_stored_account.value:
            self.data.ws_result.set("ACCOUNT NOT FOUND")
        else:
            if self.data.ws_status.value != "ACTIVE":
                self.data.ws_result.set("ACCOUNT NOT ACTIVE")
            else:
                if self.data.ws_pin.value == self.data.ws_stored_pin.value:
                    self.data.ws_result.set("ACCOUNT VERIFIED")
                else:
                    self.data.ws_result.set("INVALID PIN")

    def run(self) -> None:
        """Entry point — calls the first paragraph."""
        self.main_para()


if __name__ == "__main__":
    program = AccountVerifyProgram()
    program.run()
